### ISSUE TITLE
offer possiblity to Map vCloud organization VDC instead of just organization in Enterprise Manager

### ISSUE THREAD

**Issue by dlapointe-sherweb** [VeeamHub/veeam-plugin-for-vcd#11]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I am not sure if this should go through you guys or veeam support directly, but in Veeam enterprise Manager in the vCloud section to configure a vCloud Organization with a repository, we only have the option to select an entire organization. Would it be possible to select the organization VDC instead? We have organization that have more than one organization VDC and we would like to have each ORG VDC use a separate backup repository since the VDC are not in the same location, but with the current configuration, it is obligated to use the same repository.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by carceneaux** [comment]
Thanks for putting forward your request!

This plugin doesn't alter the behavior of the Veeam Self-Service Portal, it simply makes the portal accessible within VMware Cloud Director. As such, Feature Request for the portal should be directed to the [Veeam forums](https://forums.veeam.com/) and/or your local Veeam team.

I do have good news for you though. Veeam Backup Enterprise Manager 11 has a new Veeam-supported plugin built-in to the product. Also, it will add the ability to _assign multiple Backup Repositories to a single VCD Organization_.

If you'd like to see this functionality in action, I recommend you reach out to your local Veeam team.
