### ISSUE TITLE
Request support vCloud Director 10.2.x.xxxx

### ISSUE THREAD

**Issue by isnuryusuf** [VeeamHub/veeam-plugin-for-vcd#12]
Hi

Its possible to use this plugin for VMware Cloud Director version: 10.2.2.xxxx?

**Comment by carceneaux** [comment]
[Veeam Backup & Replication v11 is required](https://helpcenter.veeam.com/docs/backup/em/system_requirements.html?ver=110#vCD) to support VCD 10.2.

Included in v11 is a new & improved [Veeam-supported VCD plugin](https://helpcenter.veeam.com/docs/backup/em/vcd_plugin_upload_configure.html?ver=110). I recommend you migrate from this community-supported plugin to the new one.

As such, this plugin will not be updated to support Veeam Backup & Replication v11.
