### ISSUE TITLE
vCloud Director 10 support

### ISSUE THREAD

**Issue by ober72** [VeeamHub/veeam-plugin-for-vcd#2]
Hi 

I tried importing the plugin to Vcd10 but got an error stating that a "manifest.json" file could not be found. I believe this is because the plugin was written for Vcd 9.7. Therefore this is a feature request, unless I have missed something and this should also work for Vcd 10.

Thanks

**Comment by carceneaux** [comment]
Thanks for creating this @ober72!

As Veeam doesn’t support vCD 10 yet, I had yet to test. It’s been added to my roadmap.

**Comment by carceneaux** [comment]
@ober72 I just added the plugin to vCD 10 without issue. I used the [VMware Plugin Lifecycle Manager](https://veeamhub.github.io/veeam-plugin-for-vcd/plugin-deploy-plugin-manager.html) method for deployment as it's included with vCD 10 by default.

Please make sure the file you're trying to import is the `plugin.zip` file.

**Note:** *Even though the plugin is compatible with vCD 10, Veeam's Self-Service vCD portal does not support it yet.*

**Comment by ober72** [comment]
Hi Chris

Thanks we will test it.

cheers

**Comment by carceneaux** [comment]
Closing this as I've confirmed the plugin does work with vCD 10. Be on the lookout shortly for the next version of the plugin! 😊 It will add SSO functionality!
