### ISSUE TITLE
Veeam plugin issue for vCloud director

### ISSUE THREAD

**Issue by ManivelRR** [VeeamHub/veeam-plugin-for-vcd#6]
Hi Team,
We have an issue on Veeam plugin.

Vcloud director version is 9.7.0.4.
Veeam version is v10.

It was running fine till veeam 9.5 U4.After Veeam update to v10,we started facing the issue.

we followed this article https://veeamhub.github.io/veeam-plugin-for-vcd/vssp-iis-config.html

Test01 is vcloud director tenant. Already we have allocated some Quota in Veeam "Self service portal under vCloud" of veeam enterprise manager.
enterprise manager of veeam URL is https://veeamem.uslocal.com:9443

When we access the self service portal from vCloud director tenant(chrome browser),it is not re-routing of below error.

Tenant: routing to Veeam Portal
bundle.js:1 
Organization Administrator: 
true
bundle.js:1 Logged in to VSSP: true

Refused to display 'https://veeamem.uslocal.com:9443/vCloud/test01/index.aspx' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

Its working in IE browser 11 without any issues.
when we do on chrome v80 or below version,we are getting the above display error.

We are using IIS configuration(veeam server)running on Windows 2019.
In IIS-->http response section

![image](https://user-images.githubusercontent.com/49863883/76197523-4f719a80-6212-11ea-9507-0cddbee29bd7.png)

![image](https://user-images.githubusercontent.com/49863883/76197602-792ac180-6212-11ea-9b0b-460859ede007.png)

Thanks,
Manivel RR

**Comment by carceneaux** [comment]
Hi @ManivelRR,

Veeam Backup Enterprise Manager v10 uses a [different method](https://veeamhub.github.io/veeam-plugin-for-vcd/vssp-iis-config.html#enterprise-manager-v10) for setting the `Content-Security-Policy` header. As shown in your screenshot below, the field circled should be: `{C:1};{C:2};{C:3};{C:4};{C:5};{C:6};{C:7};{C:8};{C:9};{C:10};{C:11}; frame-ancestors <vCD FQDN>;`

`frame-ancestors 'self'` is actually what the URL rewrite trying to reconfigure as this tells both Chrome & Firefox **not** to allow iFrames which prohibits the vCD plugin from working.

![image](https://user-images.githubusercontent.com/17179966/76214400-07874f00-61e3-11ea-8aa8-ae08273b1d32.png)

Another issue I see in your screenshot is the `X-Frame-Options` header should be `ALLOW-FROM  https://veeamvcd.uslocal.com`

![image](https://user-images.githubusercontent.com/17179966/76214790-d3605e00-61e3-11ea-9925-bc75a61c2e8c.png)

Have you tried using the IIS configuration script - `Set-IIS-Config.ps1` - I provided with this release? This is makes configuration much easier.

**Comment by ManivelRR** [comment]
Thanks for your response.I followed that article and it was like that(allow-from vcdurl) and URL rewrite and
 {C:1};{C:2};{C:3};{C:4};{C:5};{C:6};{C:7};{C:8};{C:9};{C:10};{C:11}; frame-ancestors veeamvcd.uslocal.com;
I checked by changing one by one parameters.It was not worked.

To make it work,I added this extension in chrome browser " disable security policy header".It worked.I dont know how to make it work without any extensions? Any ideas?
IE V 11 is working fine without any extension.
Mozilla firefox is still having issue.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://VEEAMEM URL. (Reason: CORS request did not succeed).

Thanks

**Comment by carceneaux** [comment]
Please double-check your IIS configuration as this is the source of the issue. Have you tried using the [IIS configuration script](https://veeamhub.github.io/veeam-plugin-for-vcd/vssp-iis-config.html#automated-configuration) I provided with the latest release? This makes configuration much easier.

The reason the plugin is working with IE v11 is that Internet Explorer doesn't recognize the [frame-ancestors directive](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors). By installing the Chrome extension to get the plugin working, you're essentially bypassing the security built-in to Enterprise Manager to prevent spoofing and man in the middle attacks. 

Also, make sure you're putting the vCD URL in your IIS config and **not** your Enterprise Manager URL. The added IIS configuration is essentially telling EM to trust vCD.

**Comment by ManivelRR** [comment]
Thanks for response again.
I deleted the IIS configuration and done the IIS configuration again using script.

Still im ended up with the same error on chrome,

Refused to display 'https://veeamem.uslocal.com:9443/vCloud/test01/index.aspx' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self'".

**Comment by carceneaux** [comment]
It seems the URL Rewrite rule in the IIS configuration is not working. That's what is suppose to replace `frame-ancestors 'self'` with `frame-ancestors <vcd>`. Can you please provide a screenshot of the error from the developer console?

**Comment by ManivelRR** [comment]
Please refer the screenshot of IIS rule.

![image](https://user-images.githubusercontent.com/49863883/76337854-f4c56500-631d-11ea-9936-d5cf2370ce76.png)

Developer console screenshot.

![image](https://user-images.githubusercontent.com/49863883/76337401-50432300-631d-11ea-945c-da8b27783c6c.png)

**Comment by carceneaux** [comment]
Thx @ManivelRR, I also need the `content-security-policy` response header to get to the bottom of this. Easiest way to do this would be to install [this plugin](https://chrome.google.com/webstore/detail/http-headers/nioieekamcpjfleokdcdifpmclkohddp?hl=en) and then visit the self-service portal directly - i.e. `https://veeamem.uslocal.com:9443/vCloud/test01/login.aspx`.

Then, you can access the response header using the plugin:

![image](https://user-images.githubusercontent.com/17179966/76354107-3affd180-62e8-11ea-8b58-c5d8d1f52ddb.png)

**Comment by carceneaux** [comment]
Also, check for multiple instances of the `content-security-policy` header.

**Comment by ManivelRR** [comment]
Thanks again.Right from the beginning,Veeam self service portal direct login works fine without any issues.
![image](https://user-images.githubusercontent.com/49863883/76357850-7331ff00-633e-11ea-9cde-9a296fb0fcc4.png)

**Comment by carceneaux** [comment]
Thx for the screenshots @ManivelRR. I need a copy/paste of the `content-security-policy` string shown in your screenshot.

**Comment by ManivelRR** [comment]
Thanks much for your support.We uninstalled and reinstalled Veeam ES and reconfigured IIS.
Issue fixed.

**Comment by carceneaux** [comment]
Thanks for the follow-up. I'll go ahead and close this issue.
