### ISSUE TITLE
vCloud 10.1

### ISSUE THREAD

**Issue by klemmboslice** [VeeamHub/veeam-plugin-for-vcd#8]
Just curious if there are plans to support vCloud 10.1 
Love the idea of this tool and the features but already having 10.1 is causing then tenant to be unable to open the self service page in our environment.

**Comment by aledr** [comment]
I see no problem here.
Can you post a screen of your problem?

**Comment by carceneaux** [comment]
I haven’t tested 10.1 as of yet but I’ve heard others mention they have tested it with success.

Keep in mind that VBR/EM v10a is required for VCD 10.1 support.

If you recently upgraded EM, make sure you re-apply the [IIS configuration](https://veeamhub.github.io/veeam-plugin-for-vcd/vssp-iis-config.html).

As was mentioned, a screenshot or further information on the issue you’re experiencing would be helpful.

**Comment by carceneaux** [comment]
Hi @klemmboslice,

I know the weekend might've gotten this sidetracked. Were you able to resolve the issue you were experiencing?

**Comment by carceneaux** [comment]
Closing as plugin works with VCD 10.1 and VBR/EM 10a.

@klemmboslice - If you still are experiencing an issue, please open another [issue](https://github.com/VeeamHub/veeam-plugin-for-vcd/issues/new/choose) with more detailed information so I can assist.
