### ISSUE TITLE
Chrome doesn't allow login to Veeam Portal

### ISSUE THREAD

**Issue by cilcenk** [VeeamHub/veeam-plugin-for-vcd#9]
Hi all, 

On chrome version 81.0 or later plugin is not working as expected as it's not getting users successfully logining in. Other browser are not having the same issue. Could you please look into this issue?

**Comment by aledr** [comment]
I have the same here, all browsers are not allowing SSO.

**Comment by carceneaux** [comment]
Can you please post a screenshot of the error you’re seeing from the developer console of your browser? This will shed more light on the problem.

If you’re unfamiliar with this console, here’s a blog post with more info: https://support.monday.com/hc/en-us/articles/360002197259-How-to-Open-the-Developer-Console-in-your-Browser

**Comment by aledr** [comment]
Can I send It privately?
We can also do collaborative session using Webex if you prefer.

**Comment by carceneaux** [comment]
Other than the URL, the screenshot should not contain sensitive information. I only need to know the error(s) being shown. I'll add that this will be helpful for others who stumble upon this in the future.

If you're still not comfortable uploading the screenshot with the URL removed, you can email it to me:

[chris.arceneaux@veeam.com](mailto:chris.arceneaux@veeam.com)

**Comment by aledr** [comment]
Thanks for your help @carceneaux.
My case was a recent change in the SSL Certificates.
I had to edit the properties of the Cloud Servers to refresh the new certificate hash.

**Comment by cilcenk** [comment]
Alexandre's answer enlighted me ass well that it might be due to SSL certificate mismatch, so I did a bit change and seems like it's all fine now. Thanks @carceneaux  @aledr

**Comment by carceneaux** [comment]
Thanks for the follow-up! I'll go ahead and close this out.
